
# Settings for the demo site.
# `jekyll serve` does not auto-reload this file.
#
# See https://leo3418.github.io/collections/multilingual-jekyll-site/localize-strings
# for how localization works.

title: Hematite Theme
description: A Jekyll theme intended for course websites

permalink: pretty


