
# Settings for the demo site.
# `jekyll serve` does not auto-reload this file.
#
# See https://leo3418.github.io/collections/multilingual-jekyll-site/localize-strings
# for how localization works.

title: Hematite Theme
description: A Jekyll theme intended for course websites
permalink: pretty

hematite:
  sidebar:
    footer_html: 'This page was made with the Hematite Theme. <a href="https://github.com/personalizedrefrigerator/jekyll-hematite-theme">Contribute on GitHub</a>'


